/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.educatiom.login;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author SaulHernandoEcheverr
 */
public class LoginUser extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginUser.class.getName());

    Conexion instanciaConexionSQL = Conexion.getInstance();

    /**
     * Creates new form Login
     */
    public LoginUser() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Iniciar sesión");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cajaTextoUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cajaPassword = new javax.swing.JPasswordField();
        botonIniciarSesion = new javax.swing.JButton();
        botonRegistrarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Iniciar Sesión");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PersonalLogin.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(240, 240, 240));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Usuario: ");

        cajaTextoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        cajaTextoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTextoUsuarioActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(240, 240, 240));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Password: ");

        cajaPassword.setBackground(new java.awt.Color(255, 255, 255));

        botonIniciarSesion.setBackground(new java.awt.Color(255, 204, 0));
        botonIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoIniciarSesion.png"))); // NOI18N
        botonIniciarSesion.setBorderPainted(false);
        botonIniciarSesion.setContentAreaFilled(false);
        botonIniciarSesion.setFocusPainted(false);
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });

        botonRegistrarUsuario.setBackground(new java.awt.Color(255, 204, 0));
        botonRegistrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoRegistro.png"))); // NOI18N
        botonRegistrarUsuario.setBorderPainted(false);
        botonRegistrarUsuario.setContentAreaFilled(false);
        botonRegistrarUsuario.setFocusPainted(false);
        botonRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cajaTextoUsuario)
                            .addComponent(cajaPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(botonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(botonRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cajaTextoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cajaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonIniciarSesion)
                    .addComponent(botonRegistrarUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validarUsuario() {

        String password = String.valueOf(cajaPassword.getPassword());
        String usuario = cajaTextoUsuario.getText();
        
        if (password.equals("") || cajaTextoUsuario.getText().equals("")) {
            mostrarMensajeErrorAlRegistrarUsuario();
        } else {
            try{
                boolean usuarioExistente = false;
                Connection conexionSQL = instanciaConexionSQL.getConnection();
                PreparedStatement seleccion = conexionSQL.prepareStatement("select * from registros where usuario = '" + usuario + "' and contrasena='" + password + "'");
                ResultSet consulta = seleccion.executeQuery();
                if (consulta.next()) {
                    usuarioExistente = true;

                    if (usuarioExistente == true) {
                        limpiarCampos();
                        CRUD_Tablas crudTabla = new CRUD_Tablas();
                        this.setVisible(false);
                        crudTabla.setVisible(true);
                    }

                } else {
                    mostrarMensajeDeUsuarioNoEncontrado();
                }
            } catch (SQLException error) {
                System.err.println("Error: " + error);
            }

        }

    }

    private void registrarUsuario() {
        String password = String.valueOf(cajaPassword.getPassword());

        if (password.equals("") || cajaTextoUsuario.equals("")){
            mostrarMensajeErrorAlRegistrarUsuario();
        } else {
            try {
                Connection connectionSQL = instanciaConexionSQL.getConnection();
                PreparedStatement insercion = connectionSQL.prepareStatement("insert into registros(usuario, contrasena) values(?, ?)");
                insercion.setString(1, cajaTextoUsuario.getText());
                insercion.setString(2, password);
                insercion.executeUpdate();

                mostrarMensajeDeUsuarioRegistrado();
                limpiarCampos();

            } catch (SQLException error) {
                System.err.println("Error: " + error);
            }
        }

    }

    private void mostrarMensajeErrorAlRegistrarUsuario() {
        Icon icono = new ImageIcon(getClass().getResource("/images/IconError.jpg"));
        JOptionPane.showMessageDialog(rootPane, "Por favor rellene sus datos o ha ocurrido un error", "Mensaje", JOptionPane.PLAIN_MESSAGE, icono);
    }

    private void mostrarMensajeDeUsuarioRegistrado() {
        Icon icono = new ImageIcon(getClass().getResource("/images/IconoRegistro.png"));
        JOptionPane.showMessageDialog(rootPane, "Usuario registrado con éxito", "Mensaje", JOptionPane.PLAIN_MESSAGE, icono);
    }

    private void mostrarMensajeDeUsuarioNoEncontrado() {
        Icon icono = new ImageIcon(getClass().getResource("/images/IconError.jpg"));
        JOptionPane.showMessageDialog(rootPane, "Usuario no encontrado", "Mensaje", JOptionPane.PLAIN_MESSAGE, icono);

    }

    private void limpiarCampos() {
        cajaPassword.setText("");
        cajaTextoUsuario.setText("");
    }

    private void cajaTextoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTextoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTextoUsuarioActionPerformed

    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        validarUsuario();
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    private void botonRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarUsuarioActionPerformed
        registrarUsuario();
    }//GEN-LAST:event_botonRegistrarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JButton botonRegistrarUsuario;
    private javax.swing.JPasswordField cajaPassword;
    private javax.swing.JTextField cajaTextoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
    
    
    //VOY MIN 10
}
